### ISSUE TITLE
[Question] What would be the best way reuse validator modules inside other validators? 

### ISSUE THREAD

**Issue by mindreframer** [syamilmj/para#4]
Hey @syamilmj, 

thanks for this clean looking library! Any ideas how to re-use validations in the combination with embeds_one / embeds_many   macros?

**Comment by syamilmj** [comment]
Hey @mindreframer 

Thanks for the kind words! You can use validations inside `embeds_one/2` and `embeds_many/2` macros pretty much the same way that you would use it inside `validator/2` schema.

Here's an example:

```elixir
defmodule UserPara do
  use Para

  validator :update do
    required :name, :string, validator: {:validate_length, [min: 3, max: 100]}
    embeds_many :children do
      required :name, :string, validator: {:validate_length, [min: 3, max: 100]}
    end
  end
end
```

**Comment by mindreframer** [comment]
@syamilmj Thanks for the quick response! In you example there is duplication for the top-level user params and the embedded children. Would it be possible to re-use those bits? I guess currently it's not possible, but how about something like this: 

```elixir
defmodule UserPara do
  use Para

  validator :update do
    required :name, :string, validator: {:validate_length, [min: 3, max: 100]}
    ## here we recursively validate children and children's children
    embeds_many :children, validator: {UserPara, :update}
    ## or if we had a role validator
    embeds_many :roles, validator: {RolePara, :update}
  end
end
```

**Comment by syamilmj** [comment]
That's a very good suggestion. Let me find some time to look at how to tackle that use-case this week.

Just a quick thought, something like this could potentially work:

```
optional :child, :map, validator: :child_validator
```

**Comment by syamilmj** [comment]
Hey @mindreframer, this will be a useful feature and definitely appreciate the suggestion. However, I'd love to hear if there are others who'd need the same feature so that we can justify investing more time on building this feature. Closing this issue for now.
